### PR TITLE
Improve scripts

### PR DESCRIPTION
**Pull request by wladmis**
scripts: do not use P_PWD

lkrg-bootup.sh: exec P_LKRG_SYSTEMD

scripts: double-quote variables and expansions, copy file with archive mode

### CODE REVIEW

**Review by solardiz — APPROVED** [review]
LGTM, although I wouldn't use the `./` prefixes - relative paths work fine without those.

**Comment by solardiz** [comment]
I assume this has been tested and is ready to merge, correct @wladmis?

@Adam-pi3 Would you like to take a look before we merge this?

**Comment by Adam-pi3** [comment]
LGTM

**Comment by wladmis** [comment]
> I assume this has been tested and is ready to merge, correct @wladmis?

Yes, I tested it a bit.

**Pull request merged**
