### PR TITLE
Various spelling and grammar corrections

### PR DESCRIPTION
**Pull request by vt-alt**
Spelling PR as suggested by @solardiz

### CODE REVIEW

**Comment by vt-alt** [comment]
@solardiz

> Additionally, it is strongly dependend from the architecture.

This `from`, probably, needs correcting too.,

**Comment by solardiz** [comment]
I'm making some lazy edits via GitHub UI, which results in many tiny commits. Planning on doing a squash-and-merge, so don't bother with the individual commit messages.

**Comment by vt-alt** [comment]
IC. FYI: This way (if commit is edited via UI or squashed) github will mangle author's/committer's name, AFAIK. (Name will be changed to guthub user profile name, and email, possible, (depending on user's privacy setting) will be changed to github hashed email). While for such spelling commit it may be unimportant, but normal contribution is expected to be merged correctly,

**Comment by solardiz** [comment]
Good point. Here's what we got:

```
commit c97076c6826ab94121600d304ee54742f288c71a
Author: Vitalio <vt@altlinux.org>
Date:   Wed Aug 19 00:18:56 2020 +0300

    Various spelling and grammar corrections (#7)
    
    * Various spelling corrections by codespell 1.17.1
    * Various grammar corrections
    
    Signed-off-by: Vitaly Chikunov <vt@altlinux.org>
    Co-authored-by: Solar Designer <solar@openwall.com>
```

Was it perhaps Vitaly Chikunov in place of Vitalio the way you had submitted this originally? Sorry about that.

**Comment by vt-alt** [comment]
Yeah, and committer is changed too:
```
Author:     Vitalio <vt@altlinux.org>
AuthorDate: Wed Aug 19 00:18:56 2020 +0300
Commit:     GitHub <noreply@github.com>
CommitDate: Tue Aug 18 23:18:56 2020 +0200
```

**Comment by solardiz** [comment]
> Name will be changed to guthub user profile name, and email, possible, (depending on user's privacy setting) will be changed to github hashed email.

IIRC, I previously saw this happen for commits made via GitHub UI directly to the repo. I didn't expect such mangling for merely adding commits to a PR, planning to squash-and-merge.

OK, will avoid this going forward.

**Comment by vt-alt** [comment]
Interestingly, github's UI history shows that `solardiz` is committed, while in actual commit it's `GitHub <noreply@github.com>`.

**Comment by solardiz** [comment]
As discussed via private e-mail, I've just force-pushed a commit setting the desired author and committer names:

```
commit 2648a1d607d97aa7c221d3073b6efefa0f5f62cd
Author:     Vitaly Chikunov <vt@altlinux.org>
AuthorDate: Wed Aug 19 00:18:56 2020 +0300
Commit:     Solar Designer <solar@openwall.com>
CommitDate: Wed Aug 19 00:59:35 2020 +0200

    Various spelling and grammar corrections (#7)
    
    * Various spelling corrections by codespell 1.17.1
    * Various grammar corrections
    
    Signed-off-by: Vitaly Chikunov <vt@altlinux.org>
    Co-authored-by: Solar Designer <solar@openwall.com>
```

**Pull request merged**
