### PR TITLE
Fixed punctuation, word choice, and word flow

### PR DESCRIPTION
**Pull request by F0x1fy**
### Description

Made a few minor changes, particularly to punctuation, but also to word choice and word flow. For example, "might or might not" is more uncomfortable to say and read than "may or may not" as the ending "t" requires a stop. I believe these changes **may** (heh) increase readability marginally. I also did not go through and check the commands and their descriptions.

However, in regards to the manual testing portion, I believe it is still better, but rather awkward to read. Give me a few minutes and I can improve it further with some restructuring. I did this on my phone, so I would prefer to first switch to my PC for further changes.

### How Has This Been Tested?
This requires no testing as it is just minor updates to the README.

### CODE REVIEW

**Comment by F0x1fy** [comment]
I feel that this is complete now.

**Comment by solardiz** [comment]
Thanks @F0x1fy. Are you a native English speaker? I'm not, but FWIW to me your style of punctuation looks like it'd be more typical for a language other than English.

In your two commit descriptions, can you please have the title lines start with "README: " and wrap further lines at 75? If you do make these changes, then please force-push your two commits.

**Comment by F0x1fy** [comment]
I am a native English speaker, and do not see any problems with any of the changes I have made. Also, if you want me to wrap all lines past 75, that would require editing 147 lines of the README, if I am correctly understanding what you are asking.

**Comment by F0x1fy** [comment]
Crap, well. First time for everything. Haven't done a rename on a commit before, but I have a backup of the changes. One sec

**Comment by solardiz** [comment]
> if you want me to wrap all lines past 75, that would require editing 147 lines of the README, if I am correctly understanding what you are asking.

No, I meant lines in your detailed commit description, not in the README.

**Comment by F0x1fy** [comment]
That should be all of the changes. Apologies for the delay, had to learn about rebasing as I've never had to do it before.

**Comment by solardiz** [comment]
Thank you, @F0x1fy! We'd appreciate more contributions from you in the future.

**Pull request merged**
